# -*- coding: utf-8 -*-
"""Spam_ham_classification_tfidf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DC-JKD-LU0GCI65WdfOwm9mgNhMRVWTp
"""

#Here we are going to apply BOW,TFIDF,Machine Learning Algoirthms

import pandas as pd

messages=pd.read_csv('./spam.csv', encoding='latin-1')

messages=messages[['v1','v2']]
messages.columns=['label','message']

print(messages)

#we need to predict whih email is spam or ham

# Commented out IPython magic to ensure Python compatibility.
# %pip install nltk

#Data Cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
wordnetlemmatize=WordNetLemmatizer()

nltk.download('wordnet')

corpus=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[wordnetlemmatize.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)

#basically hum regular expression se usko black se replace krderhe hai

"""# Using TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X=tv.fit_transform(corpus).toarray()

tv.vocabulary_

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,messages['label'],test_size=0.2,random_state=0)

from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

y_pred=spam_detect_model.predict(X_test)

score=accuracy_score(y_test,y_pred)

print(score)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

print(cm)

from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))



"""# 1. Preprocessing and Cleaning

# 2.Train and Test Split

# 3.BOW and TF-idf(Sentences->Vectors)

# 4.Trained our Model

"""

#Why we are specifically doing this?
#training data is used for training the model ,whereas test data is used for evaluate the model
#by interchaning the step we are making sure that the model has no bit of information regarding test data

#so NLP me pehle train,test hota phir humlog BOW,tf-idf like we are preventing the data leakage
#Best Practice for solving NLP Related Question

#so splitting time ab mera code kuch aisa lagega
#X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

#aur independent feature me bhi
#X_train=cv.fit_transform(X_train).toarray()
#X_test=cv.transform(X_test).toarray()

#So is tarike se hi karna hai



