# -*- coding: utf-8 -*-
"""Spam_ham_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DC-JKD-LU0GCI65WdfOwm9mgNhMRVWTp
"""

#Here we are going to apply BOW,TFIDF,Machine Learning Algoirthms

import pandas as pd

messages=pd.read_csv('./spam.csv', encoding='latin-1')

messages=messages[['v1','v2']]
messages.columns=['label','message']

print(messages)

#we need to predict whih email is spam or ham

# Commented out IPython magic to ensure Python compatibility.
# %pip install nltk

#Data Cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
wordnetlemmatize=WordNetLemmatizer()

nltk.download('wordnet')

corpus=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[wordnetlemmatize.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)

#basically hum regular expression se usko black se replace krderhe hai

"""# Create Bag of Words"""

#Create the Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer
#For Binary BOW enable Binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

X=cv.fit_transform(corpus).toarray()

#here X is my Independent Feature

#Dependent Feature or Output Feature which is my label wala column

y=pd.get_dummies(messages['label'])

y

y=y.iloc[:,0].values

y.shape

#Train Test Splitting of data which we will do as of now
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

#X train and Y train is going to be independent and dependent data upon which i will train our data and then validate or test on the test data

from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

spam_detect_model

y_pred=spam_detect_model.predict(X_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

accuracy_score(y_test,y_pred)

#I am going to compare this like ths is my accuracy score , now just to verify as we can have imbalanced dataset also
#we will verify by classification recall with precision,recall if there is huge fluctuation then there must be problem

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))















